version: '3.8'

services:
  nookipedia-app:
    build: .
    container_name: nookipedia_live
    restart: always
    # Wir brauchen keine "ports" Sektion mehr, da NPM den Container 
    # intern über das Netzwerk auf Port 80 erreicht.
    environment:
      - APP_ENV=production
    networks:
      - npm_net

networks:
  npm_net:
    name: nginx-proxy-manager_default
    external: true