version: '3.8'

services:
  nookipedia-app:
    build: .
    container_name: nookipedia_live
    restart: always
    # Wir ändern den Host-Port auf 8080, um Konflikte mit deiner bestehenden Seite zu vermeiden.
    # Der Container hört intern weiterhin auf Port 80.
    ports:
      - "8080:80"
    environment:
      - APP_ENV=production
    # Verbindung zum bestehenden Netzwerk deines Postgres-Containers
    networks:
      - web_network

networks:
  web_network:
    external: true